### ISSUE TITLE
♿ title도 quote 없이 쓸 수 있게 해주세요 : )

### ISSUE THREAD

**Issue by l0vey0u** [dev-green-flamingo/vscode-with-tistory#1]
https://github.com/dev-green-flamingo/vscode-with-tistory/blob/64927bf23c2e61e5fb07e071b93fd1f38929f829/README.md?plain=1#L56

title만 quote가 필요하니까 일관성이 깨져요 ㅠㅠ

**Comment by aronalee** [comment]
다음 업데이트 때 반영하겠습니다. 😅
